### ISSUE TITLE
"space search" -> "blind docking" ?

### ISSUE THREAD

**Issue by UnixJunkie** [Rmadeye/autodockvina-spacesearcher#1]
I.e. docking on the whole protein surface, without prior knowledge of the binding site.

**Comment by Rmadeye** [comment]
Yes, it is blind docking.  Just found "space search" more understandable for people that did not know any docking methods previously and wanted to give it a try.

**Comment by UnixJunkie** [comment]
Well,  then you can write "space search" / "blind docking" to make it clearer.
Thanks for the clarification though.
